[project]
name = "mailer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [python-docx = "*"]

[tool.poetry.dependencies]
requests = "*"
beautifulsoup4 = "*"
python-docx = "*"
rich = "*"
